"""empty message

Revision ID: 80e201b77088
Revises: 2e18e097d042
Create Date: 2023-11-06 14:55:37.790441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e201b77088'
down_revision = '2e18e097d042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('date_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'date_time')
    # ### end Alembic commands ###
